// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PROG30000_Group9_WebApp.Services;

#nullable disable

namespace Project.Migrations
{
    [DbContext(typeof(TutorConnectDB))]
    [Migration("20231120222542_addedMultipleTutorsRelationships")]
    partial class addedMultipleTutorsRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("PROG30000_Group9_WebApp.Models.StudySession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryMode")
                        .HasColumnType("TEXT");

                    b.Property<string>("Schedule")
                        .HasColumnType("TEXT");

                    b.Property<string>("Subject")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StudySessions");
                });

            modelBuilder.Entity("PROG30000_Group9_WebApp.Models.Tutor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tutors");
                });

            modelBuilder.Entity("StudySessionTutor", b =>
                {
                    b.Property<Guid>("StudySessionsId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TutorsId")
                        .HasColumnType("TEXT");

                    b.HasKey("StudySessionsId", "TutorsId");

                    b.HasIndex("TutorsId");

                    b.ToTable("StudySessionTutor");
                });

            modelBuilder.Entity("StudySessionTutor", b =>
                {
                    b.HasOne("PROG30000_Group9_WebApp.Models.StudySession", null)
                        .WithMany()
                        .HasForeignKey("StudySessionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PROG30000_Group9_WebApp.Models.Tutor", null)
                        .WithMany()
                        .HasForeignKey("TutorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
